version: 2
updates:
  - package-ecosystem: "go"
    directory: "/"
    schedule:
      interval: "daily"
      time: 12:00

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: 12:00