name: "Link workflow"

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  semgrep:
    name: "Analyse Semgrep"
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    container:
      image: returntocorp/semgrep:1.1.0
    
    if: (github.actor != 'dependabot[bot]')

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Exécution Semgrep"
        run: semgrep ci --sarif --output=semgrep.sarif
        env:
          SEMGREP_RULES: p/default
      
      - name: "Envoie du fichier SARIF via CodeQL"
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: semgrep.sarif